import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "500", "700"],
});

const georgia = localFont({
  src: [
    {
      path: "./georgia/georgia.ttf", 
      weight: "400",
      style: "normal",
    },
    {
      path: "./georgia/georgiab.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-georgia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${georgia.variable}`}>
        <Navbar />


        {children}
        <Footer />
      </body>
    </html>
  );
}
